services:
  postgres:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: troves-indexers
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
